version: "3.8"
services:
  go-app:
    image: go:v1
    build: ./
    container_name: go1
    ports:
      - '9090:9090'
    env_file:
      - ./internship/.env
    tty: true
    stdin_open: true
    command: ["/bin/sh"]
    networks:
      - my_network
  mysql-database:
    image: mysql
    container_name: database
    ports:
      - '3306:3306'
    env_file:
      - ./internship/.env1
    networks:
      - my_network
networks:
  my_network: