apiVersion: v1
kind: Service
metadata:
  name: goapp-service
spec:
  selector:
    app: goapp-pod
  ports:
  - port: {{ .Values.goapp.port }}
    targetPort: {{ .Values.goapp.targetPort }}
    name: {{ .Values.goapp.name }}
  type: {{ .Values.goapp.type }}