apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-pod
    tier: mysql-pod
  ports:
  - port: {{ .Values.Mysql.port }}
    targetPort: {{ .Values.Mysql.targetPort }}
  type: {{ .Values.Mysql.type }}
status:
  loadBalancer: {}