apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_USER: Fady
  MYSQL_PASSWORD: '3737'
  MYSQL_TCP_PORT: '3306'
  MYSQL_ROOT_PASSWORD: '2828'
  MYSQL_DATABASE: internship